In [1]:
import numpy as np      


In [2]:
vetor1 = np.array([2, 4, 6])
vetor2 = np.array([8, 12, 18])

In [3]:
soma = vetor1 + vetor2

In [4]:
soma

array([10, 16, 24])

In [5]:
soma = np.add(vetor1, vetor2)

In [6]:
soma

array([10, 16, 24])

In [7]:
sub = vetor1 - vetor2

In [8]:
sub

array([ -6,  -8, -12])

In [9]:
np.subtract(vetor1, vetor2)

array([ -6,  -8, -12])

In [10]:
np.multiply(vetor1, vetor2)

array([ 16,  48, 108])

In [11]:
v=vetor1 ** 2

In [12]:
v

array([ 4, 16, 36])

In [13]:
np.sqrt(v)

array([2., 4., 6.])

In [14]:
np.sin(vetor1)

array([ 0.90929743, -0.7568025 , -0.2794155 ])

In [15]:
np.log2(v)

array([2.      , 4.      , 5.169925])

In [16]:
matrix1 = np.array([[1,2], [3,4]])
matrix2 = np.array([[1,1], [2,2]])

In [17]:
matrix1.shape

(2, 2)

In [18]:
matrix2.shape

(2, 2)

In [20]:
matrix1

array([[1, 2],
       [3, 4]])

In [21]:
matrix2

array([[1, 1],
       [2, 2]])

In [23]:
matrix1.ndim

2

In [24]:
matrix1+matrix2

array([[2, 3],
       [5, 6]])

In [25]:
(4)*matrix1

array([[ 4,  8],
       [12, 16]])

In [26]:
np.dot(matrix1, matrix2)

array([[ 5,  5],
       [11, 11]])

In [27]:
matrix1.dot(matrix2)

array([[ 5,  5],
       [11, 11]])

In [28]:
matrix1 @ matrix2

array([[ 5,  5],
       [11, 11]])